# Generated by Django 4.2.23 on 2026-03-01 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('nivara_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_date', models.DateField()),
                ('average_cycle_length', models.IntegerField(default=28)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cycle_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_text', models.TextField()),
                ('mood_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mood_entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='moodlog',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='avg_cycle_length',
            field=models.IntegerField(default=28),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='nivara_users', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='nivara_user_permissions', to='auth.permission'),
        ),
        migrations.DeleteModel(
            name='CycleLog',
        ),
        migrations.DeleteModel(
            name='MoodLog',
        ),
        migrations.AddField(
            model_name='moodentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cycleentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
