# Generated by Django 4.2 on 2026-03-02 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivara_app', '0002_cycleentry_moodentry_remove_moodlog_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'ordering': ['-entry_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='moodentry',
            name='emotion_type',
            field=models.CharField(choices=[('happy', 'Happy'), ('calm', 'Calm'), ('anxious', 'Anxious'), ('sad', 'Sad'), ('irritated', 'Irritated'), ('stressed', 'Stressed'), ('excited', 'Excited'), ('tired', 'Tired'), ('neutral', 'Neutral'), ('hopeful', 'Hopeful'), ('overwhelmed', 'Overwhelmed'), ('content', 'Content')], default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='entry_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='journal_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moodentry',
            name='mood_score',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
