# Generated by Django 4.2 on 2026-03-03 19:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nivara_app', '0003_alter_moodentry_options_moodentry_emotion_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_date', models.DateField()),
                ('period_end_date', models.DateField(blank=True, null=True)),
                ('flow_intensity', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('very_heavy', 'Very heavy')], default='moderate', max_length=20)),
                ('severe_pain', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('actual_period_length', models.IntegerField(blank=True, null=True)),
                ('cycle_length_from_previous', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Period Log',
                'verbose_name_plural': 'Period Logs',
                'db_table': 'period_logs',
                'ordering': ['-period_start_date'],
            },
        ),
        migrations.CreateModel(
            name='CycleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_period_start_date', models.DateField()),
                ('average_cycle_length', models.CharField(choices=[('21-24', '21-24 days'), ('25-28', '25-28 days'), ('29-32', '29-32 days'), ('33-35', '33-35 days'), ('35+', 'More than 35 days'), ('not_sure', 'Not sure')], default='25-28', max_length=20)),
                ('average_cycle_length_days', models.IntegerField(default=28)),
                ('average_period_length', models.CharField(choices=[('2-3', '2-3 days'), ('3-4', '3-4 days'), ('5-6', '5-6 days'), ('7+', '7+ days'), ('not_sure', 'Not sure')], default='5-6', max_length=20)),
                ('average_period_length_days', models.IntegerField(default=5)),
                ('cycle_regularity', models.CharField(choices=[('mostly_regular', 'Yes, mostly regular'), ('sometimes_irregular', 'Sometimes irregular'), ('very_unpredictable', 'Very unpredictable'), ('not_sure', 'Not sure')], default='mostly_regular', max_length=30)),
                ('flow_intensity_last_period', models.CharField(choices=[('light', 'Light'), ('moderate', 'Moderate'), ('heavy', 'Heavy'), ('very_heavy', 'Very heavy'), ('not_sure', 'Not sure')], default='moderate', max_length=20)),
                ('spotting_between_periods', models.CharField(choices=[('never', 'Never'), ('occasionally', 'Occasionally'), ('frequently', 'Frequently'), ('not_sure', 'Not sure')], default='never', max_length=20)),
                ('typical_pms_symptoms', models.JSONField(blank=True, default=list)),
                ('birth_control_status', models.CharField(choices=[('no', 'No'), ('pill', 'Yes – Pill'), ('hormonal_iud', 'Yes – Hormonal IUD'), ('copper_iud', 'Yes – Copper IUD'), ('patch_ring', 'Yes – Patch / Ring'), ('prefer_not_say', 'Prefer not to say')], default='no', max_length=30)),
                ('reproductive_status', models.CharField(choices=[('none', 'None'), ('trying_to_conceive', 'Trying to conceive'), ('pregnant', 'Pregnant'), ('postpartum', 'Postpartum'), ('prefer_not_say', 'Prefer not to say')], default='none', max_length=30)),
                ('is_onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cycle_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cycle Profile',
                'verbose_name_plural': 'Cycle Profiles',
                'db_table': 'cycle_profiles',
            },
        ),
        migrations.CreateModel(
            name='DailyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(default=datetime.date.today)),
                ('mood', models.JSONField(blank=True, default=list)),
                ('energy_level', models.CharField(choices=[('very_low', 'Very low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('physical_symptoms', models.JSONField(blank=True, default=list)),
                ('user_notes', models.TextField(blank=True, null=True)),
                ('cycle_day', models.IntegerField(blank=True, null=True)),
                ('cycle_phase', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Checkin',
                'verbose_name_plural': 'Daily Checkins',
                'db_table': 'daily_checkins',
                'ordering': ['-checkin_date'],
                'unique_together': {('user', 'checkin_date')},
            },
        ),
    ]
