# Generated by Django 4.2 on 2026-03-06 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivara_app', '0004_periodlog_cycleprofile_dailycheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anxiety_average',
            field=models.IntegerField(blank=True, help_text='Average anxiety level 1-10', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='energy_average',
            field=models.IntegerField(blank=True, help_text='Average energy level 1-10', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lifestyle',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('working', 'Working Professional'), ('homemaker', 'Homemaker'), ('retired', 'Retired'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sleep_average',
            field=models.IntegerField(blank=True, help_text='Average sleep quality 1-10', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
    ]
